### ISSUE TITLE
Error generated.

### ISSUE THREAD

**Issue by yamini646** [rehandalal/flask-mobility#15]
It is showing error ModuleNotFoundError: No module named ' tensorflow' on giving command :flask run

**Comment by rehandalal** [comment]
Could you please provide more context for this? A link to a repo or some kind of steps to reproduce?

**Comment by yamini646** [comment]
While trying to run the downloaded project in GitHub...we installed various
requirements including tensorflow'
After using flask run command in cmd we got an error

**Comment by rehandalal** [comment]
tensorflow is not a dependency of this library so it's hard for me to tell how this issue is related to flask-mobility. it seems like you may just have an issue with another package or with Flask itself. if you can provide a sample of code producing the error I'm happy to investigate but in the meanwhile I'm going to close this issue as it seems unrelated.
